input_mount: ''     # Path to the input directory.
lightly_mount: ''   # Path to the lightly directory.
host: 'localhost'   # Hostname for serving the data.
{
    "data": {
        "enabled": true,
        "max_size": 1000
    },
    "hydra": {
        "log": {
            "enabled": false,
            "directories": []
        }
    }
}
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .
